version: 2

run:
  timeout: 5m
  go: "1.24.3"
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - gosec
    - gocritic
    - misspell
    - revive
    - unparam
  disable:
    # - typecheck (removed, not a linter in v2)

linters-settings:
  goimports:
    local-prefixes: fm24golang
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: false
  gosec:
    excludes:
      - G104 # Audit errors not checked - we handle errors appropriately
      - G204 # Subprocess launched with variable - we validate inputs

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0