version: 2

run:
  timeout: 5m
  go: "1.25.0"
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/usage/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: standard
  # Enable specific linter.
  enable:
    - ireturn
    - gosec
    - nilnil
    - nilerr
  disable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - ireturn
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: indent-error-flow
        disabled: true
      - name: var-naming
        disabled: true
      - name: empty-block
        disabled: true
