colors = {
    "default": {
        "text_color": (64, 53, 29, 255),
        "circle_fill_color": (227, 192, 117, 255),
        "circle_outline_color": (64, 53, 29, 255),
        "rect_fill_color": (227, 192, 117, 255),
        "rect_outline_color": (64, 53, 29, 255),
        "rect_text_color": (64, 53, 29, 255),
    },
    "silver": {
        "text_color": (20, 20, 20, 255),
        "circle_fill_color": (194, 194, 193, 255),
        "circle_outline_color": (20, 20, 20, 255),
        "rect_fill_color": (194, 194, 193, 255),
        "rect_outline_color": (20, 20, 20, 255),
        "rect_text_color": (20, 20, 20, 255),
    },
    "bronze": {
        "text_color": (62, 40, 28, 255),
        "circle_fill_color": (184, 128, 97, 255),
        "circle_outline_color": (62, 40, 28, 255),
        "rect_fill_color": (184, 128, 97, 255),
        "rect_outline_color": (62, 40, 28, 255),
        "rect_text_color": (62, 40, 28, 255),
    },
    "totw": {
        "text_color": (252, 227, 152, 255),
        "circle_fill_color": (0, 0, 0, 255),
        "circle_outline_color": (252, 227, 152, 255),
        "rect_fill_color": (0, 0, 0, 255),
        "rect_outline_color": (252, 227, 152, 255),
        "rect_text_color": (252, 227, 152, 255),
    },
    "motm": {
        "text_color": (242, 242, 242, 255),
        "circle_fill_color": (10, 28, 62, 255),
        "circle_outline_color": (242, 242, 242, 255),
        "rect_fill_color": (10, 28, 62, 255),
        "rect_outline_color": (242, 242, 242, 255),
        "rect_text_color": (242, 242, 242, 255),
    },
    "if_silver": {
        "text_color": (175, 188, 200, 255),
        "circle_fill_color": (24, 24, 24, 255),
        "circle_outline_color": (175, 188, 200, 255),
        "rect_fill_color": (24, 24, 24, 255),
        "rect_outline_color": (175, 188, 200, 255),
        "rect_text_color": (175, 188, 200, 255),
    },
    "if_bronze": {
        "text_color": (226, 164, 135, 255),
        "circle_fill_color": (20, 20, 19, 255),
        "circle_outline_color": (226, 164, 135, 255),
        "rect_fill_color": (20, 20, 19, 255),
        "rect_outline_color": (226, 164, 135, 255),
        "rect_text_color": (226, 164, 135, 255),
    },
    "totgs_ucl": {
        "text_color": (255, 255, 255, 255),
        "circle_fill_color": (4, 18, 90, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (4, 18, 90, 255),
        "rect_outline_color": (255, 255, 255, 255),
        "rect_text_color": (255, 255, 255, 255),
    },
    "totgs_uel": {
        "text_color": (255, 255, 255, 255),
        "circle_fill_color": (0, 0, 0, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (0, 0, 0, 255),
        "rect_outline_color": (255, 255, 255, 255),
        "rect_text_color": (255, 255, 255, 255),
    },
    "totgs_uecl": {
        "text_color": (255, 255, 255, 255),
        "circle_fill_color": (0, 0, 0, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (0, 0, 0, 255),
        "rect_outline_color": (255, 255, 255, 255),
        "rect_text_color": (255, 255, 255, 255),
    },
    "rttk_ucl": {
        "text_color": (255, 255, 255, 255),
        "circle_fill_color": (4, 18, 90, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (4, 18, 90, 255),
        "rect_outline_color": (255, 255, 255, 255),
        "rect_text_color": (255, 255, 255, 255),
    },
    "rttk_uel": {
        "text_color": (255, 255, 255, 255),
        "circle_fill_color": (0, 0, 0, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (0, 0, 0, 255),
        "rect_outline_color": (255, 255, 255, 255),
        "rect_text_color": (255, 255, 255, 255),
    },
    "rttk_uecl": {
        "text_color": (255, 255, 255, 255),
        "circle_fill_color": (0, 0, 0, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (0, 0, 0, 255),
        "rect_outline_color": (255, 255, 255, 255),
        "rect_text_color": (255, 255, 255, 255),
    },
    "fut_champs": {
        "text_color": (246, 219, 122, 255),
        "circle_fill_color": (103, 23, 16, 255),
        "circle_outline_color": (246, 219, 122, 255),
        "rect_fill_color": (103, 23, 16, 255),
        "rect_outline_color": (246, 219, 122, 255),
        "rect_text_color": (246, 219, 122, 255),
    },
    "icon": {
        "text_color": (64, 53, 29, 255),
        "circle_fill_color": (225, 224, 226, 255),
        "circle_outline_color": (64, 53, 29, 255),
        "rect_fill_color": (225, 224, 226, 255),
        "rect_outline_color": (64, 53, 29, 255),
        "rect_text_color": (64, 53, 29, 255),
    },
    "hero": {
        "text_color": (255, 255, 255, 255),
        "circle_fill_color": (216, 100, 0, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (216, 100, 0, 255),
        "rect_outline_color": (255, 255, 255, 255),
        "rect_text_color": (255, 255, 255, 255),
    },
    "ucl_hero": {
        "text_color": (255, 255, 255, 255),
        "circle_fill_color": (5, 94, 162, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (5, 94, 162, 255),
        "rect_outline_color": (255, 255, 255, 255),
        "rect_text_color": (255, 255, 255, 255),
    },
    "toty": {
        "text_color": (255, 222, 128, 255),
        "circle_fill_color": (19, 35, 85, 255),
        "circle_outline_color": (255, 255, 255, 255),
        "rect_fill_color": (19, 35, 85, 255),
        "rect_outline_color": (255, 222, 128, 255),
        "rect_text_color": (255, 222, 128, 255),
    },
    "potm_epl": {
        "text_color": (250, 250, 250, 255),
        "circle_fill_color": (77, 29, 209, 255),
        "circle_outline_color": (250, 250, 250, 255),
        "rect_fill_color": (77, 29, 209, 255),
        "rect_outline_color": (250, 250, 250, 255),
        "rect_text_color": (250, 250, 250, 255),
    },
    "potm_bundesliga": {
        "text_color": (245, 245, 245, 255),
        "circle_fill_color": (25, 25, 25, 255),
        "circle_outline_color": (245, 245, 245, 255),
        "rect_fill_color": (25, 25, 25, 255),
        "rect_outline_color": (245, 245, 245, 255),
        "rect_text_color": (245, 245, 245, 255),
    },
    "potm_ligue1": {
        "text_color": (242, 242, 242, 255),
        "circle_fill_color": (10, 28, 62, 255),
        "circle_outline_color": (242, 242, 242, 255),
        "rect_fill_color": (10, 28, 62, 255),
        "rect_outline_color": (242, 242, 242, 255),
        "rect_text_color": (242, 242, 242, 255),
    },
    "potm_mls": {
        "text_color": (242, 242, 242, 255),
        "circle_fill_color": (10, 28, 62, 255),
        "circle_outline_color": (242, 242, 242, 255),
        "rect_fill_color": (10, 28, 62, 255),
        "rect_outline_color": (242, 242, 242, 255),
        "rect_text_color": (242, 242, 242, 255),
    },
    "potm_laliga": {
        "text_color": (242, 242, 242, 255),
        "circle_fill_color": (10, 28, 62, 255),
        "circle_outline_color": (242, 242, 242, 255),
        "rect_fill_color": (10, 28, 62, 255),
        "rect_outline_color": (242, 242, 242, 255),
        "rect_text_color": (242, 242, 242, 255),
    },
    "potm_serie_a": {
        "text_color": (0, 232, 217, 255),
        "circle_fill_color": (28, 18, 89, 255),
        "circle_outline_color": (0, 232, 217, 255),
        "rect_fill_color": (28, 18, 89, 255),
        "rect_outline_color": (0, 232, 217, 255),
        "rect_text_color": (0, 232, 217, 255),
    },
    "potm_eredivisie": {
        "text_color": (242, 242, 242, 255),
        "circle_fill_color": (10, 28, 62, 255),
        "circle_outline_color": (242, 242, 242, 255),
        "rect_fill_color": (10, 28, 62, 255),
        "rect_outline_color": (242, 242, 242, 255),
        "rect_text_color": (242, 242, 242, 255),
    },
}


position_offsets = {
    "ST": {"vertical": -75, "horizontal": 0},
    "LW": {"vertical": 0, "horizontal": -150},
    "RW": {"vertical": 0, "horizontal": 150},
    "CAM": {"vertical": -250, "horizontal": 0},
    "CDM": {"vertical": 200, "horizontal": 0},
    "RWB": {"vertical": -300, "horizontal": 0},
    "LWB": {"vertical": -300, "horizontal": 0},
}


FORMATIONS = {
    "4-3-3(2)": ["LW,ST,RW", "CM,CDM,CM", "LB,CB,CB,RB"],
    "3-5-2": ["ST,ST", "LM,CDM,CAM,CDM,RM", "CB,CB,CB"],
    "3-1-4-2": ["ST,ST", "LM,CM,CDM,CM,RM", "CB,CB,CB"],
    "3-4-1-2": ["ST,ST", "LM,CM,CAM,CM,RM", "CB,CB,CB"],
    "3-4-3 Flat": ["LW,ST,RW", "LM,CM,CM,RM", "CB,CB,CB"],
    "3-5-1-1": ["ST", "LM,CM,CAM,CM,RM", "CB,CB,CB"],
    "4-1-2-1-2": ["ST,ST", "CAM", "CM,CM", "CDM", "LB,CB,CB,RB"],
    "4-1-2-1-2 (2)": ["ST,ST", "CAM", "CM,CM", "CDM", "LB,CB,CB,RB"],
    "4-1-2-1-2 Narrow": ["ST,ST", "CAM", "CM,CM", "CDM", "LB,CB,CB,RB"],
    "4-1-2-1-2 Wide": ["ST,ST", "CAM", "LM,RM", "CDM", "LB,CB,CB,RB"],
    "4-1-3-2": ["ST,ST", "LM,CAM,RM", "CDM", "LB,CB,CB,RB"],
    "4-1-4-1": ["ST", "LM,CM,CM,RM", "CDM", "LB,CB,CB,RB"],
    "4-2-2-2": ["ST,ST", "CAM,CAM", "CDM,CDM", "LB,CB,CB,RB"],
    "4-2-3-1": ["ST", "CAM,CAM,CAM", "CDM,CDM", "LB,CB,CB,RB"],
    "4-2-3-1 (2)": ["ST", "LW,CAM,RW", "CDM,CDM", "LB,CB,CB,RB"],
    "4-2-3-1 Narrow": ["ST", "CAM,CAM,CAM", "CDM,CDM", "LB,CB,CB,RB"],
    "4-2-3-1 Wide": ["ST", "LM,CAM,RM", "CDM,CDM", "LB,CB,CB,RB"],
    "4-2-4": ["LW,ST,ST,RW", "CM,CM", "LB,CB,CB,RB"],
    "4-3-1-2": ["ST,ST", "CAM", "CM,CM,CM", "LB,CB,CB,RB"],
    "4-3-3": ["LW,ST,RW", "CM,CM,CM", "LB,CB,CB,RB"],
    "4-3-3 (3)": ["LW,ST,RW", "CDM,CM,CDM", "LB,CB,CB,RB"],
    "4-3-3 (4)": ["LW,ST,RW", "CM,CAM,CM", "LB,CB,CB,RB"],
    "4-3-3(5)": ["LW,CAM,RW", "CM,CDM,CM", "LB,CB,CB,RB"],
    "4-3-2-1": ["ST,ST,ST" "CM,CM,CM", "LB,CB,CB,RB"],
    "4-4-2": ["ST,ST", "LM,CM,CM,RM", "LB,CB,CB,RB"],
    "4-4-2 (2)": ["ST,ST", "LM,CDM,CDM,RM", "LB,CB,CB,RB"],
    "4-4-1-1": ["ST", "LM,CM,CAM,CM,RM", "LB,CB,CB,RB"],
    "4-5-1": ["ST", "LM,CAM,CM,CAM,RM", "LB,CB,CB,RB"],
    "4-5-1 Flat": ["ST", "LM,CM,CM,CM,RM", "LB,CB,CB,RB"],
    "5-1-2-2": ["ST,ST", "LM,CAM,CM,CAM,RM", "CB,CB,CB"],
    "5-2-1-2": ["ST,ST", "CM,CAM,CM", "LWB,CB,CB,CB,RWB"],
    "5-2-2-1": ["LW,ST,RW", "CM,CM", "LWB,CB,CB,CB,RWB"],
    "5-2-3": ["LW,ST,RW", "CM,CM", "LWB,CB,CB,CB,RWB"],
    "5-3-2": ["ST,ST", "CM,CM,CM", "LWB,CB,CB,CB,RWB"],
    "5-4-1": ["ST", "LM,CM,CM,RM", "LWB,CB,CB,CB,RWB"],
    "5-4-1 Diamond": ["ST", "LM, CAM, RM", "CDM", "LWB,CB,CB,CB,RWB"],
    "5-4-1 Flat": ["ST", "LM,CM,CM,RM", "LWB,CB,CB,CB,RWB"],
}


fifa_position_mapping = {
    "DC": "CB",
    "DL": "LB",
    "DR": "RB",
    "WBR": "RWB",
    "WBL": "LWB",
    "DM": "CDM",
    "MC": "CM",
    "AMC": "CAM",
    "MR": "RM",
    "ML": "LM",
    "AMR": "RW",
    "AML": "LW",
    "STC": "ST",
}


position_attribute_weights = {
    "CB": {
        "Mar": 15,
        "Tck": 15,
        "Hea": 10,
        "Str": 10,
        "Agg": 8,
        "Pos": 8,
        "Pas": 5,
        "Fir": 5,
        "Jum": 14,
        "Acc": 5,
        "Pac": 5,
    },
    "RB": {
        "Tck": 6,
        "Pos": 7,
        "Mar": 6,
        "Sta": 10,
        "Cro": 9,
        "Hea": 4,
        "Fir": 8,
        "Pas": 10,
        "Acc": 9,
        "Pac": 9,
        "Agg": 4,
        "Dri": 10,
        "Str": 5,
        "Bal": 3,
    },
    "LB": {
        "Tck": 6,
        "Pos": 7,
        "Mar": 6,
        "Sta": 10,
        "Cro": 9,
        "Hea": 4,
        "Fir": 8,
        "Pas": 10,
        "Acc": 9,
        "Pac": 9,
        "Agg": 4,
        "Dri": 10,
        "Str": 5,
        "Bal": 3,
    },
    "RWB": {
        "Tck": 5,
        "Cro": 10,
        "Pas": 10,
        "Vis": 3,
        "Fir": 8,
        "Pos": 8,
        "Mar": 7,
        "Sta": 11,
        "Dri": 11,
        "Pac": 10,
        "Acc": 10,
        "Agi": 5,
        "Fla": 2,
    },
    "LWB": {
        "Tck": 5,
        "Cro": 10,
        "Pas": 10,
        "Vis": 3,
        "Fir": 8,
        "Pos": 8,
        "Mar": 7,
        "Sta": 11,
        "Dri": 11,
        "Pac": 10,
        "Acc": 10,
        "Agi": 5,
        "Fla": 2,
    },
    "CDM": {
        "Pas": 13,
        "Pos": 12,
        "Mar": 10,
        "Tck": 10,
        "Ant": 5,
        "Wor": 10,
        "Fir": 9,
        "Vis": 8,
        "Sta": 6,
        "Str": 6,
        "Agg": 5,
        "Lon": 2,
        "Acc": 2,
        "Pac": 2,
    },
    "CM": {
        "Pas": 15,
        "Vis": 12,
        "Fir": 8,
        "Dri": 6,
        "Pos": 8,
        "OtB": 8,
        "Tck": 6,
        "Sta": 6,
        "Wor": 6,
        "Mar": 4,
        "Lon": 4,
        "Acc": 4,
        "Agi": 2,
        "Pac": 2,
        "Fin": 2,
        "Tec": 7,
    },
    "CAM": {
        "Pas": 14,
        "Vis": 12,
        "Fir": 11,
        "Dri": 13,
        "OtB": 12,
        "Fla": 4,
        "Lon": 8,
        "Tec": 8,
        "Acc": 4,
        "Agi": 6,
        "Fin": 5,
        "Pac": 3,
    },
    "RM": {
        "Cro": 10,
        "Dri": 12,
        "Pas": 8,
        "Fir": 12,
        "Vis": 8,
        "OtB": 7,
        "Sta": 10,
        "Acc": 10,
        "Pac": 10,
        "Fla": 3,
        "Agi": 3,
        "Pos": 3,
        "Fin": 2,
        "Tck": 2,
    },
    "LM": {
        "Cro": 10,
        "Dri": 12,
        "Pas": 8,
        "Fir": 12,
        "Vis": 8,
        "OtB": 7,
        "Sta": 10,
        "Acc": 10,
        "Pac": 10,
        "Fla": 3,
        "Agi": 3,
        "Pos": 3,
        "Fin": 2,
        "Tck": 2,
    },
    "RW": {
        "Cro": 8,
        "OtB": 8,
        "Dri": 9,
        "Fir": 10,
        "Lon": 5,
        "Fla": 7,
        "Fin": 6,
        "Hea": 1,
        "Vis": 5,
        "Acc": 10,
        "Pac": 10,
        "Tec": 7,
        "Cmp": 4,
        "Wor": 3,
        "Str": 2,
        "Agi": 5,
    },
    "LW": {
        "Cro": 8,
        "OtB": 8,
        "Dri": 9,
        "Fir": 10,
        "Lon": 5,
        "Fla": 7,
        "Fin": 6,
        "Hea": 1,
        "Vis": 5,
        "Acc": 10,
        "Pac": 10,
        "Tec": 7,
        "Cmp": 4,
        "Wor": 3,
        "Str": 2,
        "Agi": 5,
    },
    "ST": {
        "Fin": 15,
        "Ant": 8,
        "OtB": 10,
        "Hea": 7,
        "Lon": 5,
        "Dri": 6,
        "Fir": 8,
        "Acc": 9,
        "Pac": 7,
        "Cmp": 5,
        "Tec": 5,
        "Str": 7,
        "Fla": 2,
        "Pen": 2,
        "Pas": 2,
        "Vis": 2,
    },
}


new_attribute_mapping = {
    "PAC": [("Acc", 0.45), ("Pac", 0.55)],
    "SHO": [
        ("Fin", 0.5),
        ("Lon", 0.10),
        ("Pen", 0.05),
        ("OtB", 0.15),
        ("Tec", 0.05),
        ("Hea", 0.05),
        ("Cmp", 0.1),
    ],
    "PAS": [
        ("Pas", 0.4),
        ("Vis", 0.35),
        ("Tec", 0.05),
        ("Cro", 0.1),
        ("Fre", 0.05),
        ("Dec", 0.05),
    ],
    "DRI": [
        ("Agi", 0.1),
        ("Bal", 0.05),
        ("Dri", 0.35),
        ("Fir", 0.3),
        ("Fla", 0.15),
        ("Tec", 0.1),
    ],
    "DEF": [("Tck", 0.35), ("Mar", 0.25), ("Pos", 0.15), ("Ant", 0.1), ("Cnt", 0.15)],
    "PHY": [
        ("Agg", 0.15),
        ("Str", 0.45),
        ("Sta", 0.2),
        ("Wor", 0.1),
        ("Nat", 0.05),
        ("Jum", 0.1),
    ],
}

alt_attribute_mapping = {
    "PAC": [("Acc", 0.45), ("Pac", 0.55)],
    "SHO": [
        ("Fin", 0.3),
        ("Lon", 0.1),
        ("Pen", 0.05),
        ("OtB", 0.15),
        ("Tec", 0.15),
        ("Hea", 0.05),
        ("Cmp", 0.1),
        ("Ant", 0.05),  # Changed from dict to tuple
        ("Dec", 0.05),  # Changed from dict to tuple
    ],
    "PAS": [
        ("Pas", 0.3),
        ("Vis", 0.3),
        ("Tec", 0.15),
        ("Cro", 0.1),
        ("Fre", 0.05),
        ("Dec", 0.05),
        ("Cor", 0.05),  # Changed from dict to tuple
    ],
    "DRI": [
        ("Agi", 0.1),
        ("Bal", 0.1),
        ("Dri", 0.3),
        ("Fir", 0.3),
        ("Fla", 0.15),
        ("Tec", 0.1),
    ],
    "DEF": [
        ("Tck", 0.25),
        ("Mar", 0.2),
        ("Pos", 0.15),
        ("Dec", 0.1),
        ("Agg", 0.05),
        ("Ant", 0.1),
        ("Cnt", 0.1),
        ("Bra", 0.05),  # Ensure this is a tuple if it's supposed to be
    ],
    "PHY": [
        ("Jum", 0.1),
        ("Sta", 0.2),
        ("Wor", 0.15),
        ("Str", 0.25),
        ("Agi", 0.15),
        ("Bal", 0.15),
    ],
}

criteria_map = {
    "acrobatic.png": ["Agi", "Bal"],
    "aerial.png": ["Jum", "Hea"],
    "anticipate.png": ["Ant", "Mar"],
    "block.png": ["Pos", "Cnt"],
    "bruiser.png": ["Str", "Agg"],
    "dead_ball.png": ["Fre"],
    "finesse.png": ["Lon", "Tec"],
    "first_touch.png": ["Fir"],
    "flair.png": ["Fla"],
    "incisive_pass.png": ["Pas", "Tec"],
    "intercept.png": ["Tck", "Pos", "Mar"],
    "jockey.png": ["Mar"],
    "long_ball_pass.png": ["Pas", "Vis"],
    "pinged_pass.png": ["Pas"],
    "power_header.png": ["Hea"],
    "power_shot.png": ["Lon"],
    "press_proven.png": ["Pas", "Agi"],
    "quick_step.png": ["Acc"],
    "rapid.png": ["Pac"],
    "relentless.png": ["Sta", "Wor"],
    "slide_tackle.png": ["Tck"],
    "technical.png": ["Dri", "Agi"],
    "tiki_taka.png": ["Pas", "Dri", "Agi"],
    "trickster.png": ["Dri", "Fla"],
    "whipped_pass.png": ["Cro"],
}
nations = {
    "Afghanistan": "AFG",
    "Albania": "ALB",
    "Algeria": "ALG",
    "American Samoa": "ASA",
    "Andorra": "AND",
    "Angola": "ANG",
    "Anguilla": "AIA",
    "Antigua and Barbuda": "ATG",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "Aruba": "ARU",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Bahamas": "BAH",
    "Bahrain": "BHR",
    "Bangladesh": "BAN",
    "Barbados": "BRB",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Belize": "BLZ",
    "Benin": "BEN",
    "Bermuda": "BER",
    "Bhutan": "BHU",
    "Bolivia": "BOL",
    "Bosnia and Herzegovina": "BIH",
    "Botswana": "BOT",
    "Brazil": "BRA",
    "British Virgin Islands": "VGB",
    "Brunei": "BRU",
    "Bulgaria": "BUL",
    "Burkina Faso": "BFA",
    "Burundi": "BDI",
    "Cambodia": "CAM",
    "Cameroon": "CMR",
    "Canada": "CAN",
    "Cape Verde": "CPV",
    "Cayman Islands": "CAY",
    "Central African Republic": "CTA",
    "Chad": "CHA",
    "Chile": "CHI",
    "China": "CHN",
    "Chinese Taipei": "TPE",
    "Colombia": "COL",
    "Comoros": "COM",
    "Congo": "CGO",
    "Cook Islands": "COK",
    "Costa Rica": "CRC",
    "Croatia": "CRO",
    "Cuba": "CUB",
    "Curaçao": "CUW",
    "Cyprus": "CYP",
    "Czech Republic": "CZE",
    "Denmark": "DEN",
    "Djibouti": "DJI",
    "Dominica": "DMA",
    "Dominican Republic": "DOM",
    "DR Congo": "COD",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "El Salvador": "SLV",
    "England": "ENG",
    "Equatorial Guinea": "EQG",
    "Eritrea": "ERI",
    "Estonia": "EST",
    "Eswatini": "SWZ",
    "Ethiopia": "ETH",
    "Faroe Islands": "FRO",
    "Fiji": "FIJ",
    "Finland": "FIN",
    "France": "FRA",
    "Gabon": "GAB",
    "Gambia": "GAM",
    "Georgia": "GEO",
    "Germany": "GER",
    "Ghana": "GHA",
    "Gibraltar": "GIB",
    "Greece": "GRE",
    "Grenada": "GRN",
    "Guam": "GUM",
    "Guatemala": "GUA",
    "Guinea": "GUI",
    "Guinea-Bissau": "GNB",
    "Guyana": "GUY",
    "Haiti": "HAI",
    "Honduras": "HON",
    "Hong Kong": "HKG",
    "Hungary": "HUN",
    "Iceland": "ISL",
    "India": "IND",
    "Indonesia": "IDN",
    "Iran": "IRN",
    "Iraq": "IRQ",
    "Israel": "ISR",
    "Italy": "ITA",
    "Ivory Coast": "CIV",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Jordan": "JOR",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Kosovo": "KOS",
    "Kuwait": "KUW",
    "Kyrgyzstan": "KGZ",
    "Laos": "LAO",
    "Latvia": "LVA",
    "Lebanon": "LBN",
    "Lesotho": "LES",
    "Liberia": "LBR",
    "Libya": "LBY",
    "Liechtenstein": "LIE",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Macau": "MAC",
    "Madagascar": "MAD",
    "Malawi": "MWI",
    "Malaysia": "MAS",
    "Maldives": "MDV",
    "Mali": "MLI",
    "Malta": "MLT",
    "Mauritania": "MTN",
    "Mauritius": "MRI",
    "Mexico": "MEX",
    "Moldova": "MDA",
    "Mongolia": "MNG",
    "Montenegro": "MNE",
    "Montserrat": "MSR",
    "Morocco": "MAR",
    "Mozambique": "MOZ",
    "Myanmar": "MYA",
    "Namibia": "NAM",
    "Nepal": "NEP",
    "Netherlands": "NED",
    "New Caledonia": "NCL",
    "New Zealand": "NZL",
    "Nicaragua": "NCA",
    "Niger": "NIG",
    "Nigeria": "NGA",
    "North Korea": "PRK",
    "North Macedonia": "MKD",
    "Northern Ireland": "NIR",
    "Norway": "NOR",
    "Oman": "OMA",
    "Pakistan": "PAK",
    "Palestine": "PLE",
    "Panama": "PAN",
    "Papua New Guinea": "PNG",
    "Paraguay": "PAR",
    "Peru": "PER",
    "Philippines": "PHI",
    "Poland": "POL",
    "Portugal": "POR",
    "Puerto Rico": "PUR",
    "Qatar": "QAT",
    "Republic of Ireland": "IRL",
    "Romania": "ROU",
    "Russia": "RUS",
    "Rwanda": "RWA",
    "Saint Kitts and Nevis": "SKN",
    "Saint Lucia": "LCA",
    "Saint Vincent and the Grenadines": "VIN",
    "Samoa": "SAM",
    "San Marino": "SMR",
    "São Tomé and Príncipe": "STP",
    "Saudi Arabia": "KSA",
    "Scotland": "SCO",
    "Senegal": "SEN",
    "Serbia": "SRB",
    "Seychelles": "SEY",
    "Sierra Leone": "SLE",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Solomon Islands": "SOL",
    "Somalia": "SOM",
    "South Africa": "RSA",
    "South Korea": "KOR",
    "South Sudan": "SSD",
    "Spain": "ESP",
    "Sri Lanka": "SRI",
    "Sudan": "SDN",
    "Suriname": "SUR",
    "Sweden": "SWE",
    "Switzerland": "SUI",
    "Syria": "SYR",
    "Tahiti": "TAH",
    "Tajikistan": "TJK",
    "Tanzania": "TAN",
    "Thailand": "THA",
    "Timor-Leste": "TLS",
    "Togo": "TOG",
    "Tonga": "TGA",
    "Trinidad and Tobago": "TRI",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "Turkmenistan": "TKM",
    "Turks and Caicos Islands": "TCA",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "United Arab Emirates": "UAE",
    "United States": "USA",
    "Uruguay": "URU",
    "U.S. Virgin Islands": "VIR",
    "Uzbekistan": "UZB",
    "Vanuatu": "VAN",
    "Venezuela": "VEN",
    "Vietnam": "VIE",
    "Wales": "WAL",
    "Yemen": "YEM",
    "Zambia": "ZAM",
}
