apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube.yaml

# This allows ArgoCD Image Updater to automatically update the image
images:
  - name: ghcr.io/liamhardman/fm-dash
    newName: ghcr.io/liamhardman/fm-dash
    newTag: dev