// Centralized scatter plot configurations for the Performance page
// Grouped by category and group

export const scatterPlotConfigs = [
  // Attacking plots
  {
    category: 'attacking',
    group: 'shooting',
    title: 'Shooting Performance',
    xAxisKey: 'xG/90',
    yAxisKey: 'Gls/90',
    xAxisLabel: 'Expected Goals per 90',
    yAxisLabel: 'Goals per 90',
    quadrantLabels: {
      topRight: ['Elite', 'Over-performing'],
      topLeft: ['Clinical', 'Over-performing'],
      bottomRight: ['Wasteful', 'Under-performing'],
      bottomLeft: ['Low Threat', 'Under-performing'],
    },
  },
  {
    category: 'attacking',
    group: 'shooting',
    title: 'Shooting Efficiency',
    xAxisKey: 'Shot/90',
    yAxisKey: 'Conv %',
    xAxisLabel: 'Shots per 90',
    yAxisLabel: 'Conversion %',
    quadrantLabels: {
      topRight: ['Elite Attacker', ''],
      topLeft: ['Selective Shooter', ''],
      bottomRight: ['Inefficient Volume', ''],
      bottomLeft: ['Limited Threat', ''],
    },
  },

  // Passing plots
  {
    category: 'passing',
    group: 'creative',
    title: 'Creative Passing',
    xAxisKey: 'xA/90',
    yAxisKey: 'Asts/90',
    xAxisLabel: 'Expected Assists per 90',
    yAxisLabel: 'Assists per 90',
    quadrantLabels: {
      topRight: ['Elite Creator', ''],
      topLeft: ['Fortunate Creator', ''],
      bottomRight: ['Unlucky Creator', ''],
      bottomLeft: ['Limited Creator', ''],
    },
  },
  {
    category: 'passing',
    group: 'creative',
    title: 'Key Passes',
    xAxisKey: 'K Ps/90',
    yAxisKey: 'Asts/90',
    xAxisLabel: 'Key Passes per 90',
    yAxisLabel: 'Assists per 90',
    quadrantLabels: {
      topRight: ['Elite Creator', ''],
      topLeft: ['Clinical Passer', ''],
      bottomRight: ['Wasteful Creator', ''],
      bottomLeft: ['Limited Creator', ''],
    },
  },
  {
    category: 'passing',
    group: 'progression',
    title: 'Passing Progression',
    xAxisKey: 'Pr passes/90',
    yAxisKey: 'Pas %',
    xAxisLabel: 'Progressive Passes per 90',
    yAxisLabel: 'Pass Completion %',
    quadrantLabels: {
      topRight: ['Accurate Progressive', ''],
      topLeft: ['Selective Progressive', ''],
      bottomRight: ['Risky Progressive', ''],
      bottomLeft: ['Limited Progressive', ''],
    },
  },
  {
    category: 'passing',
    group: 'progression',
    title: 'Passing Volume',
    xAxisKey: 'Ps C/90',
    yAxisKey: 'Pas %',
    xAxisLabel: 'Passes Completed per 90',
    yAxisLabel: 'Pass Completion %',
    quadrantLabels: {
      topRight: ['Elite Passer', ''],
      topLeft: ['Accurate Passer', ''],
      bottomRight: ['Volume Passer', ''],
      bottomLeft: ['Limited Passer', ''],
    },
  },
  {
    category: 'passing',
    group: 'crossing',
    title: 'Crossing Efficiency',
    xAxisKey: 'Crs A/90',
    yAxisKey: 'Cr C/90',
    xAxisLabel: 'Crosses Attempted per 90',
    yAxisLabel: 'Crosses Completed per 90',
    quadrantLabels: {
      topRight: ['Elite Crosser', ''],
      topLeft: ['Selective Crosser', ''],
      bottomRight: ['Volume Crosser', ''],
      bottomLeft: ['Limited Crosser', ''],
    },
  },
  {
    category: 'passing',
    group: 'crossing',
    title: 'Crossing Impact',
    xAxisKey: 'Crs A/90',
    yAxisKey: 'xA/90',
    xAxisLabel: 'Crosses Attempted per 90',
    yAxisLabel: 'Expected Assists per 90',
    quadrantLabels: {
      topRight: ['Elite Crosser', ''],
      topLeft: ['Clinical Crosser', ''],
      bottomRight: ['Volume Crosser', ''],
      bottomLeft: ['Limited Crosser', ''],
    },
  },

  // Defending plots
  {
    category: 'defending',
    group: 'duels',
    title: 'Defensive Duels',
    xAxisKey: 'Tck/90',
    yAxisKey: 'Tck R',
    xAxisLabel: 'Tackles per 90',
    yAxisLabel: 'Tackle Success %',
    quadrantLabels: {
      topRight: ['Elite Ball-Winner', ''],
      topLeft: ['Conservative', ''],
      bottomRight: ['Reckless', ''],
      bottomLeft: ['Passive', ''],
    },
  },
  {
    category: 'defending',
    group: 'duels',
    title: 'Defensive Actions',
    xAxisKey: 'Tck/90',
    yAxisKey: 'Int/90',
    xAxisLabel: 'Tackles per 90',
    yAxisLabel: 'Interceptions per 90',
    quadrantLabels: {
      topRight: ['Elite Defender', ''],
      topLeft: ['Tackle Specialist', ''],
      bottomRight: ['Interception Specialist', ''],
      bottomLeft: ['Limited Defender', ''],
    },
  },
  {
    category: 'defending',
    group: 'pressing',
    title: 'Pressing Efficiency',
    xAxisKey: 'Pres C/90',
    yAxisKey: 'Poss Won/90',
    xAxisLabel: 'Pressures Completed per 90',
    yAxisLabel: 'Possession Won per 90',
    quadrantLabels: {
      topRight: ['Effective Presser', ''],
      topLeft: ['Positional Winner', ''],
      bottomRight: ['Ineffective Presser', ''],
      bottomLeft: ['Low Activity', ''],
    },
  },
  {
    category: 'defending',
    group: 'pressing',
    title: 'Pressing Impact',
    xAxisKey: 'Pres A/90',
    yAxisKey: 'Poss Won/90',
    xAxisLabel: 'Pressures Attempted per 90',
    yAxisLabel: 'Possession Won per 90',
    quadrantLabels: {
      topRight: ['Elite Presser', ''],
      topLeft: ['Selective Presser', ''],
      bottomRight: ['Ineffective Presser', ''],
      bottomLeft: ['Limited Presser', ''],
    },
  },
  {
    category: 'defending',
    group: 'aerial',
    title: 'Aerial Duels',
    xAxisKey: 'Aer A/90',
    yAxisKey: 'Hdrs W/90',
    xAxisLabel: 'Aerial Challenges per 90',
    yAxisLabel: 'Headers Won per 90',
    quadrantLabels: {
      topRight: ['Elite Aerial', ''],
      topLeft: ['Selective Winner', ''],
      bottomRight: ['Ineffective Challenger', ''],
      bottomLeft: ['Limited Aerial', ''],
    },
  },
  {
    category: 'defending',
    group: 'aerial',
    title: 'Aerial & Clearance Impact',
    xAxisKey: 'K Hdrs/90',
    yAxisKey: 'Clr/90',
    xAxisLabel: 'Key Headers per 90',
    yAxisLabel: 'Clearances per 90',
    quadrantLabels: {
      topRight: ['Elite Aerial Defender', ''],
      topLeft: ['Selective Header', ''],
      bottomRight: ['Clearance Specialist', ''],
      bottomLeft: ['Limited Aerial', ''],
    },
  },
  {
    category: 'defending',
    group: 'workrate',
    title: 'Work Rate',
    xAxisKey: 'Dist/90',
    yAxisKey: 'Sprints/90',
    xAxisLabel: 'Distance Covered per 90',
    yAxisLabel: 'Sprints per 90',
    quadrantLabels: {
      topRight: ['Elite Work Rate', ''],
      topLeft: ['Endurance Runner', ''],
      bottomRight: ['Sprint Specialist', ''],
      bottomLeft: ['Limited Movement', ''],
    },
  },
  {
    category: 'defending',
    group: 'workrate',
    title: 'Defensive Intensity',
    xAxisKey: 'Dist/90',
    yAxisKey: 'Pres A/90',
    xAxisLabel: 'Distance Covered per 90',
    yAxisLabel: 'Pressures Attempted per 90',
    quadrantLabels: {
      topRight: ['Elite Intensity', ''],
      topLeft: ['Endurance Presser', ''],
      bottomRight: ['Sprint Presser', ''],
      bottomLeft: ['Limited Intensity', ''],
    },
  },

  // Goalkeeping plots
  {
    category: 'goalkeeping',
    group: 'shotstopping',
    title: 'Shot-Stopping',
    xAxisKey: 'Con/90',
    yAxisKey: 'Sv %',
    xAxisLabel: 'Goals Conceded per 90',
    yAxisLabel: 'Save Percentage',
    quadrantLabels: {
      topRight: ['Busy & Effective', ''],
      topLeft: ['Elite Goalkeeper', ''],
      bottomRight: ['Struggling', ''],
      bottomLeft: ['Protected', ''],
    },
  },
  {
    category: 'goalkeeping',
    group: 'shotstopping',
    title: 'Shot Prevention',
    xAxisKey: 'xGP/90',
    yAxisKey: 'Con/90',
    xAxisLabel: 'Expected Goals Prevented per 90',
    yAxisLabel: 'Goals Conceded per 90',
    quadrantLabels: {
      topRight: ['Elite Shot-Stopper', ''],
      topLeft: ['Protected Keeper', ''],
      bottomRight: ['Exposed Keeper', ''],
      bottomLeft: ['Limited Impact', ''],
    },
  },
]
