/**
 * Image optimization utilities for better performance
 */

import { computed, ref } from 'vue'

/**
 * Validates if a URL is from the trusted flagcdn.com domain
 * Prevents URL injection attacks by validating the full hostname
 */
function isValidFlagCdnUrl(url) {
  if (typeof url !== 'string') return false

  try {
    const urlObj = new URL(url)
    const hostname = urlObj.hostname.toLowerCase()

    // Only allow exact domain or subdomains of flagcdn.com
    return hostname === 'flagcdn.com' || hostname.endsWith('.flagcdn.com')
  } catch (_error) {
    return false
  }
}

/**
 * Generates a flag URL from FIFA country code
 * @param {string} fifaCode - FIFA country code (e.g., 'ENG', 'ESP')
 * @returns {string} - Flag URL
 */
export function getFlagUrl(fifaCode) {
  console.log('getFlagUrl called with fifaCode:', fifaCode)
  if (!fifaCode) {
    console.log('getFlagUrl: fifaCode is null/undefined, returning null')
    return null
  }
  
  // Convert FIFA code to ISO code for flagcdn.com
  const isoCode = fifaCode.toLowerCase()
  const flagUrl = `https://flagcdn.com/w80/${isoCode}.png`
  console.log('getFlagUrl: generated URL:', flagUrl)
  return flagUrl
}

/**
 * Generates a team logo URL
 * @param {string} teamName - Team name
 * @returns {string} - Team logo URL
 */
export function getTeamLogoUrl(teamName) {
  console.log('getTeamLogoUrl called with teamName:', teamName)
  if (!teamName) {
    console.log('getTeamLogoUrl: teamName is null/undefined, returning null')
    return null
  }
  
  // Use the same approach as TeamLogo component
  // The actual logo URL will be generated by the TeamLogo component
  // which calls the backend API to get team matches and then logo URLs
  // For now, return null and let the TeamLogo component handle it
  console.log('getTeamLogoUrl: delegating to TeamLogo component for team:', teamName)
  return null
}

/**
 * Generates a player face URL
 * @param {string} playerName - Player name
 * @param {string} teamName - Team name
 * @returns {string} - Player face URL
 */
export function getPlayerFaceUrl(playerName, teamName) {
  console.log('getPlayerFaceUrl called with playerName:', playerName, 'teamName:', teamName)
  if (!playerName || !teamName) {
    console.log('getPlayerFaceUrl: playerName or teamName is null/undefined, returning null')
    return null
  }
  
  // Note: This function is called from UpgradeFinderDialog but doesn't have access to player UID
  // The actual player face URL should be generated using the player UID like in PlayerDetailDialog:
  // `/api/faces?uid=${encodeURIComponent(playerUID)}`
  // For now, return null and let the PlayerCards component handle it with the player UID
  console.log('getPlayerFaceUrl: player UID not available in this context, returning null for player:', playerName, 'team:', teamName)
  return null
}

/**
 * Creates optimized image URLs with fallbacks
 * @param {string} baseUrl - Base image URL
 * @param {object} options - Optimization options
 * @returns {object} - Object with optimized URLs and loading strategies
 */
export function createOptimizedImageUrl(baseUrl, options = {}) {
  const {
    width: _width = null,
    height: _height = null,
    format: _format = 'auto',
    quality: _quality = 80,
    fallbacks = true
  } = options

  // For external services like flagcdn.com, create optimized URLs
  // Secure domain validation to prevent URL injection
  if (isValidFlagCdnUrl(baseUrl)) {
    const webpUrl = baseUrl.replace(/\.(png|jpg|jpeg)$/, '.webp')
    return {
      webp: webpUrl,
      fallback: baseUrl,
      sources: fallbacks
        ? [
            { srcset: webpUrl, type: 'image/webp' },
            { srcset: baseUrl, type: 'image/png' }
          ]
        : null
    }
  }

  // For other images, return as-is but with WebP preference
  return {
    webp: baseUrl,
    fallback: baseUrl,
    sources: null
  }
}

/**
 * Progressive image loading component helper
 * @param {HTMLElement} imgElement - Image element
 * @param {string} src - Image source
 * @param {function} onLoad - Load callback
 * @param {function} onError - Error callback
 */
export function loadImageProgressively(imgElement, src, onLoad, onError) {
  const img = new Image()

  img.onload = () => {
    imgElement.src = src
    imgElement.classList.add('loaded')
    if (onLoad) onLoad()
  }

  img.onerror = () => {
    imgElement.classList.add('error')
    if (onError) onError()
  }

  img.src = src
}

/**
 * Lazy loading intersection observer
 */
export class LazyImageLoader {
  constructor(options = {}) {
    this.options = {
      rootMargin: '50px',
      threshold: 0.1,
      ...options
    }

    this.observer = new IntersectionObserver(this.handleIntersection.bind(this), this.options)
  }

  observe(element) {
    this.observer.observe(element)
  }

  unobserve(element) {
    this.observer.unobserve(element)
  }

  handleIntersection(entries) {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const img = entry.target
        const src = img.dataset.src

        if (src) {
          loadImageProgressively(
            img,
            src,
            () => img.removeAttribute('data-src'),
            () => {}
          )
        }

        this.observer.unobserve(img)
      }
    })
  }

  disconnect() {
    this.observer.disconnect()
  }
}

// Global lazy loader instance
export const globalLazyLoader = new LazyImageLoader()

/**
 * Image preloader for critical images
 */
export class ImagePreloader {
  constructor() {
    this.cache = new Set()
  }

  preload(src) {
    if (this.cache.has(src)) {
      return Promise.resolve()
    }

    return new Promise((resolve, reject) => {
      const img = new Image()

      img.onload = () => {
        this.cache.add(src)
        resolve()
      }

      img.onerror = reject
      img.src = src
    })
  }

  preloadMultiple(sources) {
    return Promise.allSettled(sources.map(src => this.preload(src)))
  }
}

// Global preloader instance
export const globalImagePreloader = new ImagePreloader()

/**
 * Vue composable for optimized images
 */
export function useOptimizedImage(src, options = {}) {
  const loading = ref(true)
  const error = ref(false)
  const loaded = ref(false)

  const optimizedUrls = computed(() => createOptimizedImageUrl(src.value || src, options))

  const handleLoad = () => {
    loading.value = false
    loaded.value = true
    error.value = false
  }

  const handleError = () => {
    loading.value = false
    error.value = true
    loaded.value = false
  }

  return {
    optimizedUrls,
    loading,
    error,
    loaded,
    handleLoad,
    handleError
  }
}
