// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/api_responses.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResponseMetadata contains common metadata for all API responses
type ResponseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	FromCache     bool                   `protobuf:"varint,3,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TotalCount    int32                  `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_proto_api_responses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ResponseMetadata) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ResponseMetadata) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

func (x *ResponseMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseMetadata) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// PaginationInfo contains pagination details for paginated responses
type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrevious   bool                   `protobuf:"varint,6,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_proto_api_responses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationInfo) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *PaginationInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PaginationInfo) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PaginationInfo) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

// PlayerDataResponse wraps player data with metadata and pagination
type PlayerDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Players        []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,2,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	Metadata       *ResponseMetadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Pagination     *PaginationInfo        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerDataResponse) Reset() {
	*x = PlayerDataResponse{}
	mi := &file_proto_api_responses_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDataResponse) ProtoMessage() {}

func (x *PlayerDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDataResponse.ProtoReflect.Descriptor instead.
func (*PlayerDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerDataResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *PlayerDataResponse) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *PlayerDataResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PlayerDataResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// RolesResponse wraps role data with metadata
type RolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []string               `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesResponse) Reset() {
	*x = RolesResponse{}
	mi := &file_proto_api_responses_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesResponse) ProtoMessage() {}

func (x *RolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesResponse.ProtoReflect.Descriptor instead.
func (*RolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{3}
}

func (x *RolesResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RolesResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// LeaguesResponse wraps league data with metadata
type LeaguesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leagues       []string               `protobuf:"bytes,1,rep,name=leagues,proto3" json:"leagues,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaguesResponse) Reset() {
	*x = LeaguesResponse{}
	mi := &file_proto_api_responses_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaguesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaguesResponse) ProtoMessage() {}

func (x *LeaguesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaguesResponse.ProtoReflect.Descriptor instead.
func (*LeaguesResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{4}
}

func (x *LeaguesResponse) GetLeagues() []string {
	if x != nil {
		return x.Leagues
	}
	return nil
}

func (x *LeaguesResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TeamsResponse wraps team data with metadata
type TeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []string               `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamsResponse) Reset() {
	*x = TeamsResponse{}
	mi := &file_proto_api_responses_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamsResponse) ProtoMessage() {}

func (x *TeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamsResponse.ProtoReflect.Descriptor instead.
func (*TeamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{5}
}

func (x *TeamsResponse) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *TeamsResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SearchResponse wraps search results with metadata and pagination
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_api_responses_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *SearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ErrorResponse represents API error responses
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_api_responses_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GenericResponse for simple string responses
type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_proto_api_responses_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_responses_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_responses_proto_rawDescGZIP(), []int{8}
}

func (x *GenericResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GenericResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_api_responses_proto protoreflect.FileDescriptor

const file_proto_api_responses_proto_rawDesc = "" +
	"\n" +
	"\x19proto/api_responses.proto\x12\x03api\x1a\x12proto/player.proto\"\xb0\x01\n" +
	"\x10ResponseMetadata\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x03 \x01(\bR\tfromCache\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x05R\n" +
	"totalCount\"\xbf\x01\n" +
	"\x0ePaginationInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x06 \x01(\bR\vhasPrevious\"\xcf\x01\n" +
	"\x12PlayerDataResponse\x12(\n" +
	"\aplayers\x18\x01 \x03(\v2\x0e.player.PlayerR\aplayers\x12'\n" +
	"\x0fcurrency_symbol\x18\x02 \x01(\tR\x0ecurrencySymbol\x121\n" +
	"\bmetadata\x18\x03 \x01(\v2\x15.api.ResponseMetadataR\bmetadata\x123\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x13.api.PaginationInfoR\n" +
	"pagination\"X\n" +
	"\rRolesResponse\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.api.ResponseMetadataR\bmetadata\"^\n" +
	"\x0fLeaguesResponse\x12\x18\n" +
	"\aleagues\x18\x01 \x03(\tR\aleagues\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.api.ResponseMetadataR\bmetadata\"X\n" +
	"\rTeamsResponse\x12\x14\n" +
	"\x05teams\x18\x01 \x03(\tR\x05teams\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.api.ResponseMetadataR\bmetadata\"\xb8\x01\n" +
	"\x0eSearchResponse\x12(\n" +
	"\aplayers\x18\x01 \x03(\v2\x0e.player.PlayerR\aplayers\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x121\n" +
	"\bmetadata\x18\x03 \x01(\v2\x15.api.ResponseMetadataR\bmetadata\x123\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x13.api.PaginationInfoR\n" +
	"pagination\"\x95\x01\n" +
	"\rErrorResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\x121\n" +
	"\bmetadata\x18\x04 \x01(\v2\x15.api.ResponseMetadataR\bmetadata\"X\n" +
	"\x0fGenericResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.api.ResponseMetadataR\bmetadataB\vZ\tapi/protob\x06proto3"

var (
	file_proto_api_responses_proto_rawDescOnce sync.Once
	file_proto_api_responses_proto_rawDescData []byte
)

func file_proto_api_responses_proto_rawDescGZIP() []byte {
	file_proto_api_responses_proto_rawDescOnce.Do(func() {
		file_proto_api_responses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_responses_proto_rawDesc), len(file_proto_api_responses_proto_rawDesc)))
	})
	return file_proto_api_responses_proto_rawDescData
}

var file_proto_api_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_api_responses_proto_goTypes = []any{
	(*ResponseMetadata)(nil),   // 0: api.ResponseMetadata
	(*PaginationInfo)(nil),     // 1: api.PaginationInfo
	(*PlayerDataResponse)(nil), // 2: api.PlayerDataResponse
	(*RolesResponse)(nil),      // 3: api.RolesResponse
	(*LeaguesResponse)(nil),    // 4: api.LeaguesResponse
	(*TeamsResponse)(nil),      // 5: api.TeamsResponse
	(*SearchResponse)(nil),     // 6: api.SearchResponse
	(*ErrorResponse)(nil),      // 7: api.ErrorResponse
	(*GenericResponse)(nil),    // 8: api.GenericResponse
	(*Player)(nil),             // 9: player.Player
}
var file_proto_api_responses_proto_depIdxs = []int32{
	9,  // 0: api.PlayerDataResponse.players:type_name -> player.Player
	0,  // 1: api.PlayerDataResponse.metadata:type_name -> api.ResponseMetadata
	1,  // 2: api.PlayerDataResponse.pagination:type_name -> api.PaginationInfo
	0,  // 3: api.RolesResponse.metadata:type_name -> api.ResponseMetadata
	0,  // 4: api.LeaguesResponse.metadata:type_name -> api.ResponseMetadata
	0,  // 5: api.TeamsResponse.metadata:type_name -> api.ResponseMetadata
	9,  // 6: api.SearchResponse.players:type_name -> player.Player
	0,  // 7: api.SearchResponse.metadata:type_name -> api.ResponseMetadata
	1,  // 8: api.SearchResponse.pagination:type_name -> api.PaginationInfo
	0,  // 9: api.ErrorResponse.metadata:type_name -> api.ResponseMetadata
	0,  // 10: api.GenericResponse.metadata:type_name -> api.ResponseMetadata
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_api_responses_proto_init() }
func file_proto_api_responses_proto_init() {
	if File_proto_api_responses_proto != nil {
		return
	}
	file_proto_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_responses_proto_rawDesc), len(file_proto_api_responses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_responses_proto_goTypes,
		DependencyIndexes: file_proto_api_responses_proto_depIdxs,
		MessageInfos:      file_proto_api_responses_proto_msgTypes,
	}.Build()
	File_proto_api_responses_proto = out.File
	file_proto_api_responses_proto_goTypes = nil
	file_proto_api_responses_proto_depIdxs = nil
}
